CI: Disable Mac OS
An attempt to fix error: implicit declaration of function
since I'm *only* seeing people with macs here:
https://www.google.com/search?q=cffi+%22-Wimplicit-function-declaration%22